### ISSUE TITLE
Embed feature: shared artifacts rotation (delete unused screenshots and url's from database)

### ISSUE THREAD

**Issue by sergeyKhristenko** [Gapminder/dollar-street-pages#1124]
When a user shares post using the Embed feature we will store the screenshot that they made at Amazon. And the url's to the post will be stored in database as well. If we refuse to delete them - our datastorage capacity will exceed in some time.

We just need to create a policy and decide how exactly do this.
There could be a few options:
1. Delete files by simple timeout (e.g. month or something)
2. Detect the time when each post was used (the time when it was requested from the server) and then delete most unused files
3. Something like FIFO (e.g. when datastorage hits some % use of the available space - delete the oldest screenshot)
4. Check the time when each post was used and display the entire list in CMS. And then admin could decide which post to delete.

**Comment by jheeffer** [comment]
1. I'm not sure how pricey it would get? I guess you'd use S3? Or Google storage? Isn't that quite cheap for storage size? It's more about requests?
    1. storage is $0.0022/GB/month, requests $0.004 per 10.000 requests and transfer $0.090 per GB.
    2. so if you know how big the files (in kB) are, how many you want to store and how many times you think they'll get requested costs are calculated with formula below.
    3. So with 10.000 files of 400kB and 1.000.000 requests you'd have to pay `cost(400,10000,1000000)` = $40. 
    4. What numbers do we expect (nothing exact needed, just in orders of 10 is enough. 10 requests? 1000? 1000000? We could maybe even run it through cloudflare cache?
2. You could use S3 as a cache. If the file is not found in cache, it can be built again and cached. This would require the file request to include information on what is in the file (or that info be stored in a database). But that is only necessary if storage size is the cost-driving thing. It might be requests instead?

(copy to console for easy usage)
```
let cost = (size,nFiles,nRequests) => { 
  const r = { 
    storage: (size/1024/1024)*nFiles*0.0022, 
    requests: (nRequests/10000)*0.004, 
    transfer: nRequests*(size/1024/1024)*0.090 
  }; 
  r.total = r.storage+r.requests+r.transfer; return r; 
}
```

**Comment by jheeffer** [comment]
We decided to not implement any "garbage collection" at the moment because of low costs of S3 storage. When costs start going up or that solution is not viable for other reasons, we will look at these options again.
At the moment the embed-id and which pictures are shared with that embed id are saved in the database, meaning that at a later time we can recreate the pictures on the fly using the info in the database.
Also, because the share links are dollar street links, we can always change storage-service, since direct links to the images will not be shared (apart from the `og:image` meta tag (and others) in the shared page).
