### ISSUE TITLE
Matrix Page on Mobile: country name and family income cover each other

### ISSUE THREAD

**Issue by ludmilanesvitiy** [Gapminder/dollar-street-pages#394]
## Context

Matrix Page on Mobile: country name and family income cover each other
## Steps to reproduce
1. Open https://ds-dev-consumer.firebaseapp.com/matrix?thing=546ccf730f7ddf45c017967e&countries=World&regions=World&zoom=5&row=1
2. Look at the US or UK.
## Platform

Apple Iphone 5
## Browsers

Safari, Chrome
## `name of issue` screenshot

![screenshot from 2016-05-31 12 02 58](https://cloud.githubusercontent.com/assets/18209841/15669740/7858b4dc-272a-11e6-979f-7861967a90a8.png)

**Comment by Ugmaxie** [comment]
Postponed for approving new info location. 
The way to implement word cutting is not good idea because many of countries with long names will be cut and will look like not attractive.
![wordcutting](https://cloud.githubusercontent.com/assets/7901557/15675304/0a00ccb6-274a-11e6-8432-a29805933658.png)

Way of word wraping not good idea too. Names that consists of more than one word will look good, but long names of one word will be cut.

**Comment by Ugmaxie** [comment]
Seems to be good idea to give `country` name full string at the bottom, and `income` relocate to upper right corner.
