### ISSUE TITLE
When user navigates throw pages and changes language, he couldn't open matrix page

### ISSUE THREAD

**Issue by YevheniiaMazur** [Gapminder/dollar-street-pages#937]
## Context
Issue's reproducibility 10%. Mostly it appears after changing language more then 2 times and clicking on Home button at main menu at Photographer page. After that, errors in console appear and Home buttons stop its work. Reloading page didn't help

## Steps to reproduce
1. Open console at browser
2. Change language 2 or more times at different pages.
3. Navigate throw pages 

## Expected result
There are no errors in console. Buttons home works on all pages for all languages

## Current result
With probability 10% Home buttons stop its' work and throw errors in console (screenshot attached). Reloading pages didn't help, only opening new tab stops this issue.

## Platform
Any

## Browsers
Any

## Screenshot
![errors](https://user-images.githubusercontent.com/27342505/30060086-89be1c3a-924a-11e7-8359-8c890f69de03.jpg)

**Comment by sergeyKhristenko** [comment]
I guess the issue is not with language but with "road" chart. If user firstly lands to any page without "road" chart (such as About, Donate or Map) and then clicks on any page with the 'road' chart the 'road' chart won't restore it's default value.

Steps to reproduce:
1. Go to About page
2. Reload the page
3. Navigate to matrix page (either by menu, or logo at the top left corner)
